controllers:
    resource: ../src/Controller/
    type: attribute

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: \App\Controller\InstrumentController::consulterInstrument

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument

InstrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument
