controllers:
    resource: ../src/Controller/
    type: attribute

app_cours:
    path: \cours
    controller: App\Controller\CoursController::index

coursLister:
    path: \cours\lister
    controller: App\Controller\CoursController::lister