controllers:
    resource: ../src/Controller/
    type: attribute
    
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: \App\Controller\InstrumentController::consulterInstrument

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument

InstrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouterCours

ContratPretlister:
    path: /contratPret/lister
    controller: App\Controller\ContratPretController::listerContratPret

ContratPretConsulter:
    path: /contratPret/consulter/{id}
    controller: App\Controller\ContratPretController::consulterContratPret

ContratPretAjouter:
    path: /contratPret/ajouter
    controller: App\Controller\ContratPretController::ajouterContratPret

ContratPretModifier:
    path: /contratPret/modifier/{id}
    controller: App\Controller\ContratPretController::modifierContratPret

Interventionlister:
    path: /intervention/lister
    controller: App\Controller\InterventionController::listerIntervention

InterventionConsulter:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulterIntervention

InterventionAjouter:
    path: /intervention/ajouter
    controller: App\Controller\InterventionController::ajouterIntervention

